import type { 
  UserProfile, 
  Department, 
  GovernmentDocument, 
  DocumentVersion, 
  ApprovalWorkflowStep, 
  AuditLog, 
  SystemNotification 
} from '../types';

export const INITIAL_DEPARTMENTS: Department[] = [
  {
    id: 'dept-rev',
    name: 'Revenue & Taxation',
    code: 'REV',
    description: 'Manages state taxation, land records, property revenue, and fiscal collections.',
    adminIds: ['user-superadmin', 'user-deptadmin-rev'],
    adminNames: ['Dr. Rajesh Sharma', 'Smt. Sunita Rao'],
    officerCount: 42,
    documentCount: 154,
    status: 'active',
    createdAt: '2025-01-10T09:00:00Z',
    updatedAt: '2026-08-01T10:30:00Z'
  },
  {
    id: 'dept-hlt',
    name: 'Health & Family Welfare',
    code: 'HLT',
    description: 'Oversees public healthcare infrastructure, medical supplies, and disease control.',
    adminIds: ['user-deptadmin-hlt'],
    adminNames: ['Dr. Meera Nambiar'],
    officerCount: 68,
    documentCount: 230,
    status: 'active',
    createdAt: '2025-01-10T09:00:00Z',
    updatedAt: '2026-08-05T14:15:00Z'
  },
  {
    id: 'dept-mun',
    name: 'Municipal Administration',
    code: 'MUN',
    description: 'Urban development, civic infrastructure, sanitation, and municipal bylaws.',
    adminIds: ['user-deptadmin-mun'],
    adminNames: ['Er. K. V. Subramaniam'],
    officerCount: 35,
    documentCount: 112,
    status: 'active',
    createdAt: '2025-01-12T09:00:00Z',
    updatedAt: '2026-08-08T11:20:00Z'
  },
  {
    id: 'dept-pwd',
    name: 'Public Works Department',
    code: 'PWD',
    description: 'State highways, public buildings, bridges, and civil engineering infrastructure.',
    adminIds: ['user-reviewer-pwd'],
    adminNames: ['Chief Engineer Vikram Singh'],
    officerCount: 54,
    documentCount: 198,
    status: 'active',
    createdAt: '2025-01-15T09:00:00Z',
    updatedAt: '2026-08-10T16:45:00Z'
  },
  {
    id: 'dept-edu',
    name: 'Education & Skill Development',
    code: 'EDU',
    description: 'Primary, secondary, and higher education policies, grants, and curricula.',
    adminIds: ['user-deptadmin-edu'],
    adminNames: ['Prof. Ananya Roy'],
    officerCount: 78,
    documentCount: 310,
    status: 'active',
    createdAt: '2025-01-18T09:00:00Z',
    updatedAt: '2026-08-11T09:10:00Z'
  },
  {
    id: 'dept-fin',
    name: 'Finance & Treasury',
    code: 'FIN',
    description: 'State budget allocation, financial auditing, public expenditure tracking.',
    adminIds: ['user-deptadmin-fin'],
    adminNames: ['Sanjay Gupta, IAS'],
    officerCount: 29,
    documentCount: 175,
    status: 'active',
    createdAt: '2025-01-20T09:00:00Z',
    updatedAt: '2026-08-12T08:00:00Z'
  }
];

export const DEMO_USERS: UserProfile[] = [
  {
    uid: 'user-superadmin',
    fullName: 'Dr. Rajesh Sharma',
    officialEmail: 'admin@gov.in',
    employeeId: 'EMP-GOV-001',
    departmentId: 'dept-rev',
    departmentName: 'Revenue & Taxation',
    designation: 'Principal Secretary / Super Admin',
    officeBranch: 'Central Secretariat, Block A',
    mobileNumber: '+91 98765 43210',
    role: 'super_admin',
    accountStatus: 'approved',
    emailVerified: true,
    photoURL: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=200',
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2026-08-12T10:00:00Z',
    lastLoginAt: '2026-08-12T22:30:00Z'
  },
  {
    uid: 'user-deptadmin-rev',
    fullName: 'Smt. Sunita Rao',
    officialEmail: 'deptadmin@revenue.gov.in',
    employeeId: 'EMP-REV-102',
    departmentId: 'dept-rev',
    departmentName: 'Revenue & Taxation',
    designation: 'Joint Director of Revenue',
    officeBranch: 'Revenue Bhavan, Sector 4',
    mobileNumber: '+91 98123 45678',
    role: 'department_admin',
    accountStatus: 'approved',
    emailVerified: true,
    photoURL: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=200',
    createdAt: '2025-02-10T09:00:00Z',
    updatedAt: '2026-08-10T12:00:00Z',
    lastLoginAt: '2026-08-12T18:15:00Z'
  },
  {
    uid: 'user-officer-hlt',
    fullName: 'Officer Amit Verma',
    officialEmail: 'officer@health.gov.in',
    employeeId: 'EMP-HLT-204',
    departmentId: 'dept-hlt',
    departmentName: 'Health & Family Welfare',
    designation: 'Senior Nodal Officer',
    officeBranch: 'Health Directorate, Wing C',
    mobileNumber: '+91 97654 32109',
    role: 'officer',
    accountStatus: 'approved',
    emailVerified: true,
    photoURL: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=200',
    createdAt: '2025-03-01T09:00:00Z',
    updatedAt: '2026-08-11T14:20:00Z',
    lastLoginAt: '2026-08-12T21:45:00Z'
  },
  {
    uid: 'user-reviewer-pwd',
    fullName: 'Chief Engineer Vikram Singh',
    officialEmail: 'reviewer@pwd.gov.in',
    employeeId: 'EMP-PWD-308',
    departmentId: 'dept-pwd',
    departmentName: 'Public Works Department',
    designation: 'Chief Review Officer',
    officeBranch: 'PWD HQ, Civil Lines',
    mobileNumber: '+91 96543 21098',
    role: 'reviewer',
    accountStatus: 'approved',
    emailVerified: true,
    photoURL: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=200',
    createdAt: '2025-03-15T09:00:00Z',
    updatedAt: '2026-08-09T16:00:00Z',
    lastLoginAt: '2026-08-12T19:30:00Z'
  },
  {
    uid: 'user-pending-1',
    fullName: 'Officer Ramesh Kumar',
    officialEmail: 'ramesh.k@agriculture.gov.in',
    employeeId: 'EMP-AGR-501',
    departmentId: 'dept-edu',
    departmentName: 'Agriculture & Farmers Welfare',
    designation: 'Assistant Agriculture Officer',
    officeBranch: 'District Agri Office, East Zone',
    mobileNumber: '+91 95432 10987',
    role: 'officer',
    accountStatus: 'pending',
    emailVerified: true,
    createdAt: '2026-08-12T10:15:00Z',
    updatedAt: '2026-08-12T10:15:00Z'
  },
  {
    uid: 'user-pending-2',
    fullName: 'Dr. Priya Sundaram',
    officialEmail: 'priya.s@education.gov.in',
    employeeId: 'EMP-EDU-882',
    departmentId: 'dept-edu',
    departmentName: 'Education & Skill Development',
    designation: 'Deputy Educational Inspector',
    officeBranch: 'State Edu Directorate',
    mobileNumber: '+91 94321 09876',
    role: 'officer',
    accountStatus: 'pending',
    emailVerified: true,
    createdAt: '2026-08-12T14:40:00Z',
    updatedAt: '2026-08-12T14:40:00Z'
  }
];

export const INITIAL_DOCUMENTS: GovernmentDocument[] = [
  {
    id: 'doc-rev-001',
    documentNumber: 'DOC-2026-REV-001',
    title: 'State Tax Revenue Optimization & Compliance Policy 2026-27',
    description: 'Comprehensive guidelines for digital GST compliance, automated audit trailing, and municipal tax collection procedures across all districts.',
    departmentId: 'dept-rev',
    departmentName: 'Revenue & Taxation',
    category: 'Policy',
    status: 'Approved',
    priority: 'Urgent',
    confidentiality: 'Internal',
    ownerId: 'user-superadmin',
    ownerName: 'Dr. Rajesh Sharma',
    ownerEmail: 'admin@gov.in',
    currentVersion: 2,
    storagePath: 'documents/dept-rev/doc-rev-001/version-2/State_Tax_Revenue_Policy_2026.pdf',
    fileUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    fileName: 'State_Tax_Revenue_Policy_2026.pdf',
    fileSize: 2458000,
    mimeType: 'application/pdf',
    createdAt: '2026-07-15T10:00:00Z',
    updatedAt: '2026-08-01T15:30:00Z',
    createdBy: 'user-superadmin',
    tags: ['Taxation', 'Revenue', 'GST', 'Policy', '2026'],
    assignedReviewerId: 'user-deptadmin-rev',
    assignedReviewerName: 'Smt. Sunita Rao',
    remarks: 'Approved by State Finance Cabinet after secondary committee review.',
    effectiveDate: '2026-09-01'
  },
  {
    id: 'doc-hlt-004',
    documentNumber: 'DOC-2026-HLT-004',
    title: 'District Hospital Modernization & Digital EHR Procurement Directive',
    description: 'Procurement framework and standard specifications for Electronic Health Records (EHR) systems in 14 district government hospitals.',
    departmentId: 'dept-hlt',
    departmentName: 'Health & Family Welfare',
    category: 'Circular',
    status: 'Under Review',
    priority: 'High',
    confidentiality: 'Confidential',
    ownerId: 'user-officer-hlt',
    ownerName: 'Officer Amit Verma',
    ownerEmail: 'officer@health.gov.in',
    currentVersion: 1,
    storagePath: 'documents/dept-hlt/doc-hlt-004/version-1/EHR_Procurement_Framework.pdf',
    fileUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    fileName: 'EHR_Procurement_Framework.pdf',
    fileSize: 1840000,
    mimeType: 'application/pdf',
    createdAt: '2026-08-02T11:20:00Z',
    updatedAt: '2026-08-06T09:15:00Z',
    createdBy: 'user-officer-hlt',
    tags: ['Health', 'Procurement', 'EHR', 'Hospital', 'Digital Health'],
    assignedReviewerId: 'user-superadmin',
    assignedReviewerName: 'Dr. Rajesh Sharma',
    remarks: 'Awaiting technical budget verification from Health Finance Nodal.'
  },
  {
    id: 'doc-mun-012',
    documentNumber: 'DOC-2026-MUN-012',
    title: 'Smart Municipal Solid Waste Processing & Recycling Bylaws 2026',
    description: 'Notification regarding mandatory segregation of bio-degradable waste and municipal penalty framework for non-compliant commercial complexes.',
    departmentId: 'dept-mun',
    departmentName: 'Municipal Administration',
    category: 'Gazette',
    status: 'Submitted',
    priority: 'Normal',
    confidentiality: 'Public',
    ownerId: 'user-officer-hlt',
    ownerName: 'Officer Amit Verma',
    ownerEmail: 'officer@health.gov.in',
    currentVersion: 1,
    storagePath: 'documents/dept-mun/doc-mun-012/version-1/Waste_Management_Bylaws.pdf',
    fileUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    fileName: 'Waste_Management_Bylaws.pdf',
    fileSize: 3120000,
    mimeType: 'application/pdf',
    createdAt: '2026-08-08T14:00:00Z',
    updatedAt: '2026-08-08T14:00:00Z',
    createdBy: 'user-officer-hlt',
    tags: ['Municipal', 'Waste Management', 'Gazette', 'Public Notice'],
    assignedReviewerId: 'user-deptadmin-rev',
    assignedReviewerName: 'Smt. Sunita Rao'
  },
  {
    id: 'doc-pwd-009',
    documentNumber: 'DOC-2026-PWD-009',
    title: 'National Highway Extension Bridge Safety Audit SOP',
    description: 'Standard Operating Procedures for quarterly structural safety audits of elevated bridge corridors and overpasses.',
    departmentId: 'dept-pwd',
    departmentName: 'Public Works Department',
    category: 'Order',
    status: 'Approved',
    priority: 'High',
    confidentiality: 'Internal',
    ownerId: 'user-reviewer-pwd',
    ownerName: 'Chief Engineer Vikram Singh',
    ownerEmail: 'reviewer@pwd.gov.in',
    currentVersion: 3,
    storagePath: 'documents/dept-pwd/doc-pwd-009/version-3/Bridge_Safety_Audit_SOP.pdf',
    fileUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    fileName: 'Bridge_Safety_Audit_SOP.pdf',
    fileSize: 4200000,
    mimeType: 'application/pdf',
    createdAt: '2026-06-10T08:30:00Z',
    updatedAt: '2026-08-10T11:45:00Z',
    createdBy: 'user-reviewer-pwd',
    tags: ['PWD', 'Safety Audit', 'Infrastructure', 'Bridge'],
    remarks: 'Finalized and circulated to all executive engineers.'
  },
  {
    id: 'doc-edu-015',
    documentNumber: 'DOC-2026-EDU-015',
    title: 'Higher Education Digital Research Grant Allocation Guidelines',
    description: 'Directives for state university research grant disbursement, proposal evaluation criteria, and expenditure auditing.',
    departmentId: 'dept-edu',
    departmentName: 'Education & Skill Development',
    category: 'Report',
    status: 'Draft',
    priority: 'Low',
    confidentiality: 'Restricted',
    ownerId: 'user-officer-hlt',
    ownerName: 'Officer Amit Verma',
    ownerEmail: 'officer@health.gov.in',
    currentVersion: 1,
    storagePath: 'documents/dept-edu/doc-edu-015/version-1/Research_Grant_Guidelines.pdf',
    fileUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    fileName: 'Research_Grant_Guidelines.pdf',
    fileSize: 1250000,
    mimeType: 'application/pdf',
    createdAt: '2026-08-11T16:00:00Z',
    updatedAt: '2026-08-11T16:00:00Z',
    createdBy: 'user-officer-hlt',
    tags: ['Education', 'Grants', 'Research', 'Universities']
  },
  {
    id: 'doc-fin-003',
    documentNumber: 'DOC-2026-FIN-003',
    title: 'State Treasury Quarterly Expenditure & Budget Execution Audit Q2',
    description: 'Fiscal analysis report covering state expenditure against allocated Q2 budget heads across all major government departments.',
    departmentId: 'dept-fin',
    departmentName: 'Finance & Treasury',
    category: 'Financial',
    status: 'Approved',
    priority: 'Urgent',
    confidentiality: 'Confidential',
    ownerId: 'user-superadmin',
    ownerName: 'Dr. Rajesh Sharma',
    ownerEmail: 'admin@gov.in',
    currentVersion: 1,
    storagePath: 'documents/dept-fin/doc-fin-003/version-1/Q2_Treasury_Audit_Report.pdf',
    fileUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    fileName: 'Q2_Treasury_Audit_Report.pdf',
    fileSize: 5890000,
    mimeType: 'application/pdf',
    createdAt: '2026-08-01T09:00:00Z',
    updatedAt: '2026-08-04T17:00:00Z',
    createdBy: 'user-superadmin',
    tags: ['Finance', 'Audit', 'Treasury', 'Q2 Budget', 'Expenditure']
  }
];

export const INITIAL_VERSIONS: DocumentVersion[] = [
  {
    id: 'ver-rev-001-v1',
    documentId: 'doc-rev-001',
    versionNumber: 1,
    changeDescription: 'Initial draft submission of state tax revenue optimization policy.',
    storagePath: 'documents/dept-rev/doc-rev-001/version-1/State_Tax_Revenue_Policy_v1.pdf',
    fileUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    fileName: 'State_Tax_Revenue_Policy_v1.pdf',
    fileSize: 2200000,
    uploadedBy: 'user-superadmin',
    uploadedByName: 'Dr. Rajesh Sharma',
    createdAt: '2026-07-15T10:00:00Z'
  },
  {
    id: 'ver-rev-001-v2',
    documentId: 'doc-rev-001',
    versionNumber: 2,
    changeDescription: 'Incorporated Cabinet Committee amendments on digital GST penalties.',
    storagePath: 'documents/dept-rev/doc-rev-001/version-2/State_Tax_Revenue_Policy_2026.pdf',
    fileUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    fileName: 'State_Tax_Revenue_Policy_2026.pdf',
    fileSize: 2458000,
    uploadedBy: 'user-superadmin',
    uploadedByName: 'Dr. Rajesh Sharma',
    createdAt: '2026-08-01T15:30:00Z'
  }
];

export const INITIAL_WORKFLOWS: ApprovalWorkflowStep[] = [
  {
    id: 'wf-rev-001-1',
    documentId: 'doc-rev-001',
    stage: 'Uploaded',
    actorId: 'user-superadmin',
    actorName: 'Dr. Rajesh Sharma',
    actorRole: 'Super Admin',
    action: 'submitted',
    remarks: 'Document created and initial metadata verified.',
    timestamp: '2026-07-15T10:00:00Z',
    versionNumber: 1
  },
  {
    id: 'wf-rev-001-2',
    documentId: 'doc-rev-001',
    stage: 'Review',
    actorId: 'user-deptadmin-rev',
    actorName: 'Smt. Sunita Rao',
    actorRole: 'Department Admin',
    action: 'under_review',
    remarks: 'Departmental review completed. Forwarded to Cabinet Finance Committee.',
    timestamp: '2026-07-22T14:15:00Z',
    versionNumber: 1
  },
  {
    id: 'wf-rev-001-3',
    documentId: 'doc-rev-001',
    stage: 'Approval',
    actorId: 'user-superadmin',
    actorName: 'Dr. Rajesh Sharma',
    actorRole: 'Super Admin',
    action: 'approved',
    remarks: 'Final executive approval granted. Status updated to Approved.',
    timestamp: '2026-08-01T15:30:00Z',
    versionNumber: 2
  }
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'log-101',
    actorId: 'user-superadmin',
    actorName: 'Dr. Rajesh Sharma',
    actorEmail: 'admin@gov.in',
    actorRole: 'super_admin',
    action: 'SYSTEM_LOGIN',
    resourceType: 'auth',
    resourceId: 'user-superadmin',
    details: 'Successful secure login via HTTPS (Port 443) with email/password.',
    ipAddress: '10.14.20.105',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) GovDoc/1.0',
    result: 'success',
    timestamp: '2026-08-12T22:30:00Z'
  },
  {
    id: 'log-102',
    actorId: 'user-superadmin',
    actorName: 'Dr. Rajesh Sharma',
    actorEmail: 'admin@gov.in',
    actorRole: 'super_admin',
    action: 'DOCUMENT_APPROVE',
    resourceType: 'document',
    resourceId: 'doc-rev-001',
    details: 'Approved document DOC-2026-REV-001 "State Tax Revenue Optimization Policy 2026-27".',
    ipAddress: '10.14.20.105',
    userAgent: 'GovDoc Secure Engine v2.4',
    result: 'success',
    timestamp: '2026-08-01T15:30:00Z'
  },
  {
    id: 'log-103',
    actorId: 'user-officer-hlt',
    actorName: 'Officer Amit Verma',
    actorEmail: 'officer@health.gov.in',
    actorRole: 'officer',
    action: 'DOCUMENT_UPLOAD',
    resourceType: 'document',
    resourceId: 'doc-hlt-004',
    details: 'Uploaded document version 1 (EHR_Procurement_Framework.pdf, 1.84MB) with Confidentiality: Confidential.',
    ipAddress: '10.22.18.42',
    result: 'success',
    timestamp: '2026-08-02T11:20:00Z'
  },
  {
    id: 'log-104',
    actorId: 'user-pending-1',
    actorName: 'Officer Ramesh Kumar',
    actorEmail: 'ramesh.k@agriculture.gov.in',
    actorRole: 'officer',
    action: 'OFFICER_REGISTRATION_SUBMITTED',
    resourceType: 'user',
    resourceId: 'user-pending-1',
    details: 'Submitted officer registration request for Agriculture & Farmers Welfare department. Account status set to PENDING.',
    ipAddress: '10.33.40.12',
    result: 'success',
    timestamp: '2026-08-12T10:15:00Z'
  }
];

export const INITIAL_NOTIFICATIONS: SystemNotification[] = [
  {
    id: 'notif-1',
    userId: 'user-superadmin',
    title: 'New Officer Registration Request',
    message: 'Officer Ramesh Kumar (Agriculture Dept) has submitted a registration request pending your approval.',
    type: 'registration',
    read: false,
    link: '/admin/registrations',
    createdAt: '2026-08-12T10:15:00Z'
  },
  {
    id: 'notif-2',
    userId: 'user-officer-hlt',
    title: 'Document Under Review',
    message: 'Your document DOC-2026-HLT-004 "District Hospital Modernization" was assigned for technical review.',
    type: 'document',
    read: true,
    link: '/documents/doc-hlt-004',
    createdAt: '2026-08-06T09:15:00Z'
  },
  {
    id: 'notif-3',
    userId: 'user-superadmin',
    title: 'Security Audit Log Alert',
    message: 'System Security Check: 100% of network traffic routed through HTTPS (Port 443). App Check Active.',
    type: 'system',
    read: true,
    link: '/status',
    createdAt: '2026-08-12T00:00:00Z'
  }
];
